<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>77a54f50-b453-4abe-bebc-ea139f917462</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_form_pickers_html</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[2]/ul[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='form-pickers\.html']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>