<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cae460e2-ecda-4700-8f55-b2309ae4a42e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[1]/div[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.wysihtml5-toolbar .dropdown-toggle</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn dropdown-toggle')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn dropdown-toggle</value>
        <webElementGuid>8b05f252-9f84-4450-9ffc-1d3adf968009</webElementGuid>
    </webElementProperties>
</WebElementEntity>