<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>37000687-0966-4726-96b6-fe1c63b90e2b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[1]/div[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.wysihtml5-toolbar .dropdown-toggle</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn dropdown-toggle')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn dropdown-toggle</value>
        <webElementGuid>dbce25fe-1557-4d9a-ad3e-68bd5f6c61f2</webElementGuid>
    </webElementProperties>
</WebElementEntity>