<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a1f2b81d-6d3b-44c7-9d13-6ff06d7dfc05</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[1]/div[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.wysihtml5-toolbar .dropdown-toggle</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn dropdown-toggle')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn dropdown-toggle</value>
        <webElementGuid>b8f69865-c094-4134-a942-7d3173519193</webElementGuid>
    </webElementProperties>
</WebElementEntity>